import Head from 'next/head'
import { Header } from '../../components/header'
import { PageTitle } from "../../components/pageTitle";
import { ContactLink } from "../../components/contactLink";
import styles from "./barcelonete.module.css";

export default function Barcelonete() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Barcelonete | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#111111" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <PageTitle title="Barcelonete" description="User Experience Research" />
        <section className={styles.projectInfo}>
          <h2>About the project</h2>
          <p>For my HBO school project, I did research into the user experience of the website of Barcelonete. Barcelonete is a clothing brand that has been around for about three years now. The main question during this research was &quot;how could the user experience of the website be improved, so that the target group no longer has problems with using the webshop.&quot;</p>
          <p>To answer the main question, I took multiple steps during this project. These steps are divided into 4 phases as follows:</p>
          <strong>Research</strong>
          <ul>
            <li>Interviews</li>
            <li>Testing the current website</li>
            <li>Writing down the userneeds</li>
            <li>Researching competitive companies</li>
          </ul>
          <strong>Concept</strong>
          <ul>
            <li>Creating a journey map</li>
            <li>Creating concepts</li>
          </ul>
          <strong>Design</strong>
          <ul>
            <li>Creating a styleguide</li>
            <li>Creating wireframes</li>
            <li>Creating Hi-fi prototype</li>
          </ul>
          <strong>Testing</strong>
          <ul>
            <li>Testing the Hi-fi prototype</li>
          </ul>
          <p>After completing these steps, the result if a hi-fi prototype that solves the problem.</p>
          <a target="_blank" rel="noreferrer" className={styles.cta} href="https://xd.adobe.com/view/8abd4b30-5391-4e93-995b-bfae7df5251a-dfee/">Take a look</a>
        </section>
        <ContactLink />
      </main>
      <footer></footer>
    </div>
  )
}
