import Head from 'next/head'
import { Header } from '../../components/header'
import styles from '../../styles/Contact.module.css'

export default function Soulance() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
          Soulance
      </main>
      <footer>
      </footer>
    </div>
  )
}
