import Head from 'next/head'
import { Header } from '../components/header'
import styles from '../styles/About.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
          About
      </main>
      <footer>
      </footer>
    </div>
  )
}
