import Head from 'next/head'
import { Header } from '../components/header'
import styles from '../styles/Contact.module.css'

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
          Contact
      </main>
      <footer>
      </footer>
    </div>
  )
}
