import Head from "next/head";
import Link from "next/link";
import { Header } from "../components/header";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <div className={styles.hero}>
          <section>
            <span className={styles.name}>Julian van Beek</span>
            <span className={styles.function}>Web Designer</span>
          </section>
          <section className={styles.characteristics}>
            <span>Creative</span>
            <span>Tech-savvy</span>
            <span>Passionated</span>
            <span>Eager to learn</span>
            <span>Customer oriented</span>
            <span>Result driven</span>
          </section>
          <Link href="/portfolio">
            <a className={styles.cta}>View Projects</a>
          </Link>

          <span className={styles.mouse}>
            <span></span>
          </span>
        </div>

        <div >
          <h1>test</h1>
        </div>
      </main>
    </div>
  );
}
