import Head from 'next/head'
import { Header } from '../components/header'
import styles from '../styles/Portfolio.module.css'

export default function Portfolio() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
          portfolio
      </main>
      <footer>
      </footer>
    </div>
  )
}
