import Head from "next/head";
import { Header } from "../components/header";
import { PageTitle } from "../components/pageTitle";
import { Project } from "../components/project";
import { ContactLink } from "../components/contactLink";
import styles from "../styles/Portfolio.module.css";

export default function Portfolio() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#111111" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <PageTitle title="Portfolio" description="Projects I have worked on" />
        <div className={styles.projects}>
        <Project tags={['Design', 'School']} title="Barcelonete" image="https://i.postimg.cc/SsgDjJx7/barcelonete.png" pageLink="barcelonete" />
              <Project tags={['design', 'school']} title="Greenpeace Plastic Campaign" image="https://i.postimg.cc/cCY3hbHx/greenpeace.png" pageLink="greenpeace" comingSoon />
        </div>
        <ContactLink />
      </main>
      <footer></footer>
    </div>
  );
}
